name: ci

on:
  push:
  pull_request:

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: cmake --build build --config Release

      - name: Test (Windows)
        if: runner.os == 'Windows'
        run: ctest --test-dir build --output-on-failure -C Release

      - name: Build (Unix)
        if: runner.os != 'Windows'
        run: cmake --build build

      - name: Test (Unix)
        if: runner.os != 'Windows'
        run: ctest --test-dir build --output-on-failure
